# Generated by Django 5.2.11 on 2026-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Proposed"),
                    ("ONGOING", "Ongoing"),
                    ("DELAYED", "Delayed"),
                    ("COMPLETED", "Completed"),
                ],
                default="PROPOSED",
                max_length=10,
            ),
        ),
    ]
