# Generated by Django 5.2.11 on 2026-02-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone_name", models.CharField(max_length=200)),
                (
                    "milestone_order",
                    models.PositiveIntegerField(
                        help_text="Order of milestone execution"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight of milestone in percentage",
                        max_digits=5,
                    ),
                ),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("is_critical_path", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "db_table": "milestones",
                "ordering": ["project", "milestone_order"],
                "unique_together": {("project", "milestone_order")},
            },
        ),
    ]
