# Generated by Django 5.2.11 on 2026-02-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engineers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineer",
            name="role",
            field=models.CharField(
                choices=[("ENGINEER", "Engineer"), ("SUPERVISOR", "Supervisor")],
                default="Engineer",
                max_length=50,
            ),
        ),
    ]
