# Generated by Django 5.2.11 on 2026-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ward_no",
                    models.PositiveIntegerField(default=16, help_text="Ward number"),
                ),
                ("municipality", models.CharField(default="Kathmandu", max_length=100)),
                ("district", models.CharField(default="Kathmandu", max_length=100)),
                ("province", models.CharField(default="Bagmati", max_length=100)),
                ("place_or_street", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": "locations",
                "ordering": ["ward_no", "place_or_street"],
            },
        ),
    ]
