# Generated by Django 5.2.11 on 2026-02-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "road_length_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "road_width_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road",
                        to="projects.project",
                    ),
                ),
                (
                    "road_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lookups.roadtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Road",
                "verbose_name_plural": "Roads",
                "db_table": "road_details",
            },
        ),
    ]
