# Generated by Django 5.2.11 on 2026-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contractor_name", models.CharField(max_length=200)),
                ("ward_no", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contractor",
                "verbose_name_plural": "Contractors",
                "db_table": "contractors",
                "ordering": ["contractor_name"],
            },
        ),
    ]
