# Generated by Django 5.2.11 on 2026-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="company_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="company_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="company_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="contractor_type",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="district",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="latest_renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="municipality",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="pan_vat_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="contractors/pan_vat_certificates/"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="pan_vat_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="registration_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contractors/registration_certificates/",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="registration_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="suchidarta_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
