# Generated by Django 5.2.11 on 2026-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0002_contractor_address_contractor_company_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractor",
            name="ward_no",
        ),
    ]
